### ISSUE TITLE
Imcomplete array type

### ISSUE THREAD

**Issue by TApplencourt** [alcf-perfengr/cast-to-yaml#2]
```
char a[];
char a[25];
```
Give
```
  ---
  declarations:
  - name: a
    type:
      kind: array
      type:
        kind: char
        name: char
  - name: a
    type:
      kind: array
      type:
        kind: char
        name: char
      length: '25'
```
`a` should be deduplicated.
